services:
  - type: web
    name: example-app
    env: node
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      chmod +x ./gradlew
      ./gradlew build
    startCommand: npm start
